
sudo: false

language: php

php: 7.2

# cache composer downloads so installing is quicker
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    
notifications:
  email:
    on_success: never
    on_failure: always
    
install:
    - composer install
    - php security-checker.phar security:check composer.lock
    - php php-cs-fixer-v2.phar fix . --rules=@Symfony